baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ascent Data Solutions'
themes="hugo-theme-air"
paginate = 1
DisqusShortname = ""
Copyright = "All rights reserved - 2022"
canonifyurls = true

[author]
  name = "syui"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "From Data Science to customized BI solutions"
  cover = "images/user.jpg"
  author = "syui"
  authorlocation = ""
  authorwebsite = "https://syui.cf/hugo-theme-air"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "syui"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
